create table army (
    id bigint generated by default as identity,
    name varchar(255),
    battle_size varchar(255) check (battle_size in ('INCURSION','STRIKE_FORCE','ONSLAUGHT')),
    detachment varchar(255),
    faction varchar(255) check (faction in ('ADEPTA_SORORITAS')),
    primary key (id)
);

create table unit (
    id bigint generated by default as identity,
    name varchar(255),
    faction varchar(255) check (faction in ('ADEPTA_SORORITAS')),
    cost integer not null,
    type varchar(255) check (type in ('CHARACTER','BATTLELINE','DEDICATED_TRANSPORT','OTHER_DATASHEETS','ALLIED_UNITS')),
    primary key (id)
);

create table army_entry (
    army_id bigint not null,
    units_id bigint not null,
    warlord_id bigint not null
);


alter table if exists army_units
add constraint FKl1f4il99on08imqsn4gwlly1s
foreign key (units_id)
references unit;

alter table if exists army_units
add constraint FK61koxat2emts2q54taohe3u4b
foreign key (warlord_id)
references unit;

alter table if exists army_units
add constraint FK61koxat2emts2q54taohe3u4a
foreign key (army_id)
references army;

